### PR TITLE
Spelling

### PR DESCRIPTION
**Pull request by jsoref**
Generated by https://github.com/jsoref/spelling `f`; to maintain your repo, please consider `fchurn`

### CODE REVIEW

**Comment by nkcmr** [comment]
@jsoref hi! thanks for the contribution :) — would you mind squashing these commits into one please?

**Comment by jsoref** [comment]
Sure. I always start w/ distinct commits because it's easier for people to review/reject by word family, and it makes merging/rebasing easier. But once people are happy, I don't mind folding/squashing.

**Comment by jsoref** [comment]
@nkcmr: done

**Comment by nkcmr** [comment]
@jsoref hi! it has taken me a while to get around to it, but i've fixed up the build — if you wouldn't mind re-basing off of master, i'll go ahead and merge this once the builds are ✅ !

**Comment by jsoref** [comment]
@nkcmr : rebased

**Pull request merged**
